// src/service-worker.js
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Precache all of the assets generated by your build process.
export function register() {
  // eslint-disable-next-line no-restricted-globals
precacheAndRoute(self.__WB_MANIFEST || []);
// Cache images with a Cache First strategy
registerRoute(/\.(?:png|jpg|jpeg|svg|gif)$/,
  new CacheFirst({
    cacheName: 'image-cache',
    plugins: [
      new ExpirationPlugin({
        // Keep at most 50 entries in the cache
        maxEntries: 50,
        // Don't keep any entries for more than 30 days
        maxAgeSeconds: 24 * 60 * 60,
        // Automatically clean up any outdated caches
        purgeOnQuotaError: true,
      }),
    ],
  })
);
}
